title: "Thamindu's Blog"
email: ""
description: "My personal website documenting my AI, ML, and NLP learning journey."
baseurl: "" 
url: "https://thamidu02.github.io"

github_username: thamidu02
twitter_username: ""

# Theme
theme: minima

# Plugins
plugins:
  - jekyll-feed

# Navigation (Minima uses header_pages)
header_pages:
  - about.md

# Markdown options
markdown: kramdown

# Exclude unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor